@startuml

left to right direction
skinparam linetype polyline
skinparam ArrowStraight true

actor "Basic Listener" as a
actor "Premium Listener" as b
actor "Guest" as c

rectangle "System Boundary" {
usecase "View Song/Playlist/Artists details" as u1

usecase "View Song/Playlist/Artists from Recommendations" as u2
usecase "View Song/Playlist/Artists from Trending" as u3
usecase "View Song/Playlist/Artists from Favorites" as u4

usecase "Listen Online to Song/Playlist" as u5
usecase "Add/Remove Songs/Playlist from Favorites" as u6
usecase "Share Song/Playlist/Artists" as u7
usecase "Follow Playlist/Artists" as u8

usecase "Sign up for Subscription" as u9
usecase "Renew/Cancel Subscription" as u20
rectangle "Authentication" {
usecase "Sign in" as u13
usecase "Sign up" as u14
usecase "Recover Account" as u15
}

usecase "Listen Premium to Song/Playlist" as u16
usecase "Listen Offline to Song/Playlist" as u17
usecase "Download Song/Playlist" as u18
usecase "Create/Update/Delete Playlist" as u19
usecase "Modify Playlist Access Level" as u21
}
a-u1
a-u2
a--u3
a--u4
a--u5
a--u6
a--u7
a--u8
a--u9

c-up-u13
c-up-u14
c-up-u15

b-up-u16
b-up-u17
b-up-u18
b-up-u19
b-up-u20
b-up-u21

u14-[hidden]up-u2
u13-[hidden]up-u1
u15-[hidden]up-u3

u16-[hidden]up-u4
u17-[hidden]up-u8
u18-[hidden]up-u6
u19-[hidden]up-u5
u20-[hidden]up-u9
u21-[hidden]up-u7

a <|-- b: extends
@enduml