@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary TrendingArtistsLinkView
boundary TrendingArtistsView
boundary LoginView
participant ViewTrendingArtistsController
control ViewTrendingArtistsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant TrendAnalyzer <<Gateway>>
participant ViewTrendingArtistsPresenter <<OutputBoundary>>

"Guest/Listener" -> TrendingArtistsLinkView: click on navigatable element
activate "Guest/Listener"
activate TrendingArtistsLinkView

TrendingArtistsLinkView -> TrendingArtistsView: redirect
deactivate TrendingArtistsLinkView
activate TrendingArtistsView

TrendingArtistsView -> ViewTrendingArtistsController: pass RequestObject\n(paginationRequest)
activate ViewTrendingArtistsController

alt OK
    ViewTrendingArtistsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingArtistsController -> ViewTrendingArtistsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewTrendingArtistsController
    activate ViewTrendingArtistsInteractor

    ViewTrendingArtistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewTrendingArtistsInteractor <- AuthTokenGenerator: true
    deactivate AuthTokenGenerator

    ViewTrendingArtistsInteractor -> TrendAnalyzer: show trending Artists\n(paginationRequest)
    activate TrendAnalyzer
    return artists
    deactivate TrendAnalyzer

    ViewTrendingArtistsInteractor ->> ViewTrendingArtistsPresenter: pass ResponseModel\n(artists)
    deactivate ViewTrendingArtistsInteractor
    activate ViewTrendingArtistsPresenter

    ViewTrendingArtistsPresenter ->> TrendingArtistsView: repackage & upate ViewModel\n(artists)
    deactivate ViewTrendingArtistsPresenter

    TrendingArtistsView -> "Guest/Listener": see the result of the interaction
    deactivate TrendingArtistsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewTrendingArtistsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingArtistsController
    activate "Guest/Listener"
    activate TrendingArtistsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewTrendingArtistsController -> LoginView: redirect
    deactivate TrendingArtistsView
    deactivate ViewTrendingArtistsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewTrendingArtistsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingArtistsController
    activate "Guest/Listener"
    activate TrendingArtistsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingArtistsController -> ViewTrendingArtistsInteractor: repackage & pass RequestModel\n(authToken, artistId)
    deactivate ViewTrendingArtistsController
    activate ViewTrendingArtistsInteractor

    ViewTrendingArtistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewTrendingArtistsInteractor ->> ViewTrendingArtistsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingArtistsInteractor
    activate ViewTrendingArtistsPresenter

    ViewTrendingArtistsPresenter ->> TrendingArtistsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingArtistsPresenter

    TrendingArtistsView -> LoginView: redirect
    deactivate TrendingArtistsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
