@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary RecommendedArtistsLinkView
boundary RecommendedArtistsView
boundary LoginView
participant ViewRecommendedArtistsController
control ViewRecommendedArtistsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant Recommendator <<Gateway>>
participant ViewRecommendedArtistsPresenter <<OutputBoundary>>

"Guest/Listener" -> RecommendedArtistsLinkView: click on navigatable element
activate "Guest/Listener"
activate RecommendedArtistsLinkView

RecommendedArtistsLinkView -> RecommendedArtistsView: redirect
deactivate RecommendedArtistsLinkView
activate RecommendedArtistsView

RecommendedArtistsView -> ViewRecommendedArtistsController: pass RequestObject\n(paginationRequest)
activate ViewRecommendedArtistsController

alt OK
    ViewRecommendedArtistsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedArtistsController -> ViewRecommendedArtistsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewRecommendedArtistsController
    activate ViewRecommendedArtistsInteractor

    ViewRecommendedArtistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewRecommendedArtistsInteractor <- AuthTokenGenerator: true

    ViewRecommendedArtistsInteractor -> AuthTokenGenerator: get Listener ID from authentication token\n(authToken)
    ViewRecommendedArtistsInteractor <- AuthTokenGenerator: listenerId
    deactivate AuthTokenGenerator

    ViewRecommendedArtistsInteractor -> Recommendator: show recommended Artists for Listener\n(listenerId, paginationRequest)
    activate Recommendator
    return artists
    deactivate Recommendator

    ViewRecommendedArtistsInteractor ->> ViewRecommendedArtistsPresenter: pass ResponseModel\n(artists)
    deactivate ViewRecommendedArtistsInteractor
    activate ViewRecommendedArtistsPresenter

    ViewRecommendedArtistsPresenter ->> RecommendedArtistsView: repackage & upate ViewModel\n(artists)
    deactivate ViewRecommendedArtistsPresenter

    RecommendedArtistsView -> "Guest/Listener": see the result of the interaction
    deactivate RecommendedArtistsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewRecommendedArtistsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedArtistsController
    activate "Guest/Listener"
    activate RecommendedArtistsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewRecommendedArtistsController -> LoginView: redirect
    deactivate RecommendedArtistsView
    deactivate ViewRecommendedArtistsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewRecommendedArtistsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedArtistsController
    activate "Guest/Listener"
    activate RecommendedArtistsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedArtistsController -> ViewRecommendedArtistsInteractor: repackage & pass RequestModel\n(authToken, artistId)
    deactivate ViewRecommendedArtistsController
    activate ViewRecommendedArtistsInteractor

    ViewRecommendedArtistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewRecommendedArtistsInteractor ->> ViewRecommendedArtistsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedArtistsInteractor
    activate ViewRecommendedArtistsPresenter

    ViewRecommendedArtistsPresenter ->> RecommendedArtistsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedArtistsPresenter

    RecommendedArtistsView -> LoginView: redirect
    deactivate RecommendedArtistsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
