@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary RecommendedSongsLinkView
boundary RecommendedSongsView
boundary LoginView
participant ViewRecommendedSongsController
control ViewRecommendedSongsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant Recommendator <<Gateway>>
participant ViewRecommendedSongsPresenter <<OutputBoundary>>

"Guest/Listener" -> RecommendedSongsLinkView: click on navigatable element
activate "Guest/Listener"
activate RecommendedSongsLinkView

RecommendedSongsLinkView -> RecommendedSongsView: redirect
deactivate RecommendedSongsLinkView
activate RecommendedSongsView

RecommendedSongsView -> ViewRecommendedSongsController: pass RequestObject\n(paginationRequest)
activate ViewRecommendedSongsController

alt OK
    ViewRecommendedSongsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedSongsController -> ViewRecommendedSongsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewRecommendedSongsController
    activate ViewRecommendedSongsInteractor

    ViewRecommendedSongsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewRecommendedSongsInteractor <- AuthTokenGenerator: true

    ViewRecommendedSongsInteractor -> AuthTokenGenerator: get Listener ID from authentication token\n(authToken)
    ViewRecommendedSongsInteractor <- AuthTokenGenerator: listenerId
    deactivate AuthTokenGenerator

    ViewRecommendedSongsInteractor -> Recommendator: show recommended Songs for Listener\n(listenerId, paginationRequest)
    activate Recommendator
    return songs
    deactivate Recommendator

    ViewRecommendedSongsInteractor ->> ViewRecommendedSongsPresenter: pass ResponseModel\n(songs)
    deactivate ViewRecommendedSongsInteractor
    activate ViewRecommendedSongsPresenter

    ViewRecommendedSongsPresenter ->> RecommendedSongsView: repackage & upate ViewModel\n(songs)
    deactivate ViewRecommendedSongsPresenter

    RecommendedSongsView -> "Guest/Listener": see the result of the interaction
    deactivate RecommendedSongsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewRecommendedSongsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedSongsController
    activate "Guest/Listener"
    activate RecommendedSongsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewRecommendedSongsController -> LoginView: redirect
    deactivate RecommendedSongsView
    deactivate ViewRecommendedSongsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewRecommendedSongsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedSongsController
    activate "Guest/Listener"
    activate RecommendedSongsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedSongsController -> ViewRecommendedSongsInteractor: repackage & pass RequestModel\n(authToken, songId)
    deactivate ViewRecommendedSongsController
    activate ViewRecommendedSongsInteractor

    ViewRecommendedSongsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewRecommendedSongsInteractor ->> ViewRecommendedSongsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedSongsInteractor
    activate ViewRecommendedSongsPresenter

    ViewRecommendedSongsPresenter ->> RecommendedSongsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedSongsPresenter

    RecommendedSongsView -> LoginView: redirect
    deactivate RecommendedSongsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
