@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary TrendingSongsLinkView
boundary TrendingSongsView
boundary LoginView
participant ViewTrendingSongsController
control ViewTrendingSongsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant TrendAnalyzer <<Gateway>>
participant ViewTrendingSongsPresenter <<OutputBoundary>>

"Guest/Listener" -> TrendingSongsLinkView: click on navigatable element
activate "Guest/Listener"
activate TrendingSongsLinkView

TrendingSongsLinkView -> TrendingSongsView: redirect
deactivate TrendingSongsLinkView
activate TrendingSongsView

TrendingSongsView -> ViewTrendingSongsController: pass RequestObject\n(paginationRequest)
activate ViewTrendingSongsController

alt OK
    ViewTrendingSongsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingSongsController -> ViewTrendingSongsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewTrendingSongsController
    activate ViewTrendingSongsInteractor

    ViewTrendingSongsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewTrendingSongsInteractor <- AuthTokenGenerator: true
    deactivate AuthTokenGenerator

    ViewTrendingSongsInteractor -> TrendAnalyzer: show trending Songs\n(paginationRequest)
    activate TrendAnalyzer
    return songs
    deactivate TrendAnalyzer

    ViewTrendingSongsInteractor ->> ViewTrendingSongsPresenter: pass ResponseModel\n(songs)
    deactivate ViewTrendingSongsInteractor
    activate ViewTrendingSongsPresenter

    ViewTrendingSongsPresenter ->> TrendingSongsView: repackage & upate ViewModel\n(songs)
    deactivate ViewTrendingSongsPresenter

    TrendingSongsView -> "Guest/Listener": see the result of the interaction
    deactivate TrendingSongsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewTrendingSongsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingSongsController
    activate "Guest/Listener"
    activate TrendingSongsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewTrendingSongsController -> LoginView: redirect
    deactivate TrendingSongsView
    deactivate ViewTrendingSongsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewTrendingSongsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingSongsController
    activate "Guest/Listener"
    activate TrendingSongsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingSongsController -> ViewTrendingSongsInteractor: repackage & pass RequestModel\n(authToken, songId)
    deactivate ViewTrendingSongsController
    activate ViewTrendingSongsInteractor

    ViewTrendingSongsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewTrendingSongsInteractor ->> ViewTrendingSongsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingSongsInteractor
    activate ViewTrendingSongsPresenter

    ViewTrendingSongsPresenter ->> TrendingSongsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingSongsPresenter

    TrendingSongsView -> LoginView: redirect
    deactivate TrendingSongsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
