@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary TrendingPlaylistsLinkView
boundary TrendingPlaylistsView
boundary LoginView
participant ViewTrendingPlaylistsController
control ViewTrendingPlaylistsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant TrendAnalyzer <<Gateway>>
participant ViewTrendingPlaylistsPresenter <<OutputBoundary>>

"Guest/Listener" -> TrendingPlaylistsLinkView: click on navigatable element
activate "Guest/Listener"
activate TrendingPlaylistsLinkView

TrendingPlaylistsLinkView -> TrendingPlaylistsView: redirect
deactivate TrendingPlaylistsLinkView
activate TrendingPlaylistsView

TrendingPlaylistsView -> ViewTrendingPlaylistsController: pass RequestObject\n(paginationRequest)
activate ViewTrendingPlaylistsController

alt OK
    ViewTrendingPlaylistsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingPlaylistsController -> ViewTrendingPlaylistsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewTrendingPlaylistsController
    activate ViewTrendingPlaylistsInteractor

    ViewTrendingPlaylistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewTrendingPlaylistsInteractor <- AuthTokenGenerator: true
    deactivate AuthTokenGenerator

    ViewTrendingPlaylistsInteractor -> TrendAnalyzer: show trending Playlists\n(paginationRequest)
    activate TrendAnalyzer
    return playlists
    deactivate TrendAnalyzer

    ViewTrendingPlaylistsInteractor ->> ViewTrendingPlaylistsPresenter: pass ResponseModel\n(playlists)
    deactivate ViewTrendingPlaylistsInteractor
    activate ViewTrendingPlaylistsPresenter

    ViewTrendingPlaylistsPresenter ->> TrendingPlaylistsView: repackage & upate ViewModel\n(playlists)
    deactivate ViewTrendingPlaylistsPresenter

    TrendingPlaylistsView -> "Guest/Listener": see the result of the interaction
    deactivate TrendingPlaylistsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewTrendingPlaylistsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingPlaylistsController
    activate "Guest/Listener"
    activate TrendingPlaylistsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewTrendingPlaylistsController -> LoginView: redirect
    deactivate TrendingPlaylistsView
    deactivate ViewTrendingPlaylistsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewTrendingPlaylistsController -> AuthTokenRepository: get authentication token
    activate ViewTrendingPlaylistsController
    activate "Guest/Listener"
    activate TrendingPlaylistsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewTrendingPlaylistsController -> ViewTrendingPlaylistsInteractor: repackage & pass RequestModel\n(authToken, playlistId)
    deactivate ViewTrendingPlaylistsController
    activate ViewTrendingPlaylistsInteractor

    ViewTrendingPlaylistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewTrendingPlaylistsInteractor ->> ViewTrendingPlaylistsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingPlaylistsInteractor
    activate ViewTrendingPlaylistsPresenter

    ViewTrendingPlaylistsPresenter ->> TrendingPlaylistsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewTrendingPlaylistsPresenter

    TrendingPlaylistsView -> LoginView: redirect
    deactivate TrendingPlaylistsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
