@startuml

hide footbox
skinparam BackgroundColor transparent

actor "Guest/Listener"
boundary RecommendedPlaylistsLinkView
boundary RecommendedPlaylistsView
boundary LoginView
participant ViewRecommendedPlaylistsController
control ViewRecommendedPlaylistsInteractor <<InputBoundary>>
participant AuthTokenRepository <<Gateway>>
participant AuthTokenGenerator <<Gateway>>
participant Recommendator <<Gateway>>
participant ViewRecommendedPlaylistsPresenter <<OutputBoundary>>

"Guest/Listener" -> RecommendedPlaylistsLinkView: click on navigatable element
activate "Guest/Listener"
activate RecommendedPlaylistsLinkView

RecommendedPlaylistsLinkView -> RecommendedPlaylistsView: redirect
deactivate RecommendedPlaylistsLinkView
activate RecommendedPlaylistsView

RecommendedPlaylistsView -> ViewRecommendedPlaylistsController: pass RequestObject\n(paginationRequest)
activate ViewRecommendedPlaylistsController

alt OK
    ViewRecommendedPlaylistsController -> AuthTokenRepository: get authentication token
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedPlaylistsController -> ViewRecommendedPlaylistsInteractor: repackage & pass RequestModel\n(authToken, paginationRequest)
    deactivate ViewRecommendedPlaylistsController
    activate ViewRecommendedPlaylistsInteractor

    ViewRecommendedPlaylistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    ViewRecommendedPlaylistsInteractor <- AuthTokenGenerator: true

    ViewRecommendedPlaylistsInteractor -> AuthTokenGenerator: get Listener ID from authentication token\n(authToken)
    ViewRecommendedPlaylistsInteractor <- AuthTokenGenerator: listenerId
    deactivate AuthTokenGenerator

    ViewRecommendedPlaylistsInteractor -> Recommendator: show recommended Playlists for Listener\n(listenerId, paginationRequest)
    activate Recommendator
    return playlists
    deactivate Recommendator

    ViewRecommendedPlaylistsInteractor ->> ViewRecommendedPlaylistsPresenter: pass ResponseModel\n(playlists)
    deactivate ViewRecommendedPlaylistsInteractor
    activate ViewRecommendedPlaylistsPresenter

    ViewRecommendedPlaylistsPresenter ->> RecommendedPlaylistsView: repackage & upate ViewModel\n(playlists)
    deactivate ViewRecommendedPlaylistsPresenter

    RecommendedPlaylistsView -> "Guest/Listener": see the result of the interaction
    deactivate RecommendedPlaylistsView
    deactivate "Guest/Listener"

    newpage

else Error: Authentication token not found
    ViewRecommendedPlaylistsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedPlaylistsController
    activate "Guest/Listener"
    activate RecommendedPlaylistsView
    activate AuthTokenRepository
    return None
    deactivate AuthTokenRepository

    ViewRecommendedPlaylistsController -> LoginView: redirect
    deactivate RecommendedPlaylistsView
    deactivate ViewRecommendedPlaylistsController
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

else Error: Authnetication token invalid
    ViewRecommendedPlaylistsController -> AuthTokenRepository: get authentication token
    activate ViewRecommendedPlaylistsController
    activate "Guest/Listener"
    activate RecommendedPlaylistsView
    activate AuthTokenRepository
    return Some(authToken)
    deactivate AuthTokenRepository

    ViewRecommendedPlaylistsController -> ViewRecommendedPlaylistsInteractor: repackage & pass RequestModel\n(authToken, playlistId)
    deactivate ViewRecommendedPlaylistsController
    activate ViewRecommendedPlaylistsInteractor

    ViewRecommendedPlaylistsInteractor -> AuthTokenGenerator: verify authentication token
    activate AuthTokenGenerator
    return false
    deactivate AuthTokenGenerator

    ViewRecommendedPlaylistsInteractor ->> ViewRecommendedPlaylistsPresenter: pass ResponseModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedPlaylistsInteractor
    activate ViewRecommendedPlaylistsPresenter

    ViewRecommendedPlaylistsPresenter ->> RecommendedPlaylistsView: repackage & update ViewModel\n(Err(AuthTokenInvalid))
    deactivate ViewRecommendedPlaylistsPresenter

    RecommendedPlaylistsView -> LoginView: redirect
    deactivate RecommendedPlaylistsView
    activate LoginView

    LoginView -> "Guest/Listener": see the result of the interaction
    deactivate LoginView
    deactivate "Guest/Listener"

end

@enduml
