@startuml

left to right direction
hide empty members
skinparam BackgroundColor transparent

class User <<struct>> {
  + id: Uuid
  + credentials: UserCredentials
}

class UserCredentials <<struct>> {
  + username: String
  + password: String
}

UserCredentials -- User

class Listener <<struct>> {
  + metadata: ListenerMetadata
  + subscripion: ListenerSubscription
  + preferences: ListenerPreferences
}

Listener <|-- User

class ListenerMetadata <<struct>> {
  + email: String
  + dateOfBirth: Date
  + biography: Option<String>
  + gender: String
  + location: String
  + language: String
}

ListenerMetadata -- Listener

class ListenerContent <<struct>> {
  + playlistIds: Vec<Uuid>
  + favourites: ListenerFavourites
}

ListenerContent -- Listener

class ListenerFavourites <<struct>> {
  + songIds: Vec<Uuid>
  + playlistIds: Vec<Uuid>
  + artistIds: Vec<Uuid>
}

ListenerFavourites -- ListenerContent

ListenerFollows -- ListenerContent

enum ListenerSubscription <<enum>> {
}

ListenerSubscription -- Listener

class Free <<variant>> {
}

Free -- ListenerSubscription

class Premium <<variant>> {
  + started: DateTime
  + expires: DateTime
}

Premium -- ListenerSubscription

class Cancelled <<variant>> {
  + started: DateTime
  + cancelled: DateTime
}

Cancelled -- ListenerSubscription

class Expired <<variant>> {
  + started: DateTime
  + expired: DateTime
}

Expired -- ListenerSubscription

class ListenerPreferences <<struct>> {
  + darkModeEnabled: bool
  + explicitContentEnabled: bool
  + autoplayEnabled: bool
}

ListenerPreferences -- Listener

class Artist <<struct>> {
  + metadata: ArtistMetadata
  + content: ArtistContent
  + analytics: ArtistAnalytics
}

Artist <|-- User

class ArtistMetadata <<struct>> {
  + email: String
  + dateOfBirth: Date
  + displayName: String
  + biography: Option<String>
  + socialLinks: Vec<String>
  + genres: Vec<String>
  + avatarUri: String
}

ArtistMetadata -- Artist

class ArtistContent <<struct>> {
  + singleIds: Vec<Uuid>
  + albumIds: Vec<Uuid>
}

ArtistContent -- Artist

class ArtistAnalytics <<struct>> {
  + playCount: usize
  + favouritesCount: usize
}

ArtistAnalytics -- Artist

class Song <<struct>> {
  + id: Uuid
  + metadata: SongMetadata
  + audio: SongAudio
  + analytics: SongAnalytics
}

class SongMetadata <<struct>> {
  + title: String
  + artistIds: Vec<Uuid>
  + lyrics: Option<String>
  + duration: Duration
}

SongMetadata -- Song

class SongAudio <<struct>> {
  + basicUri: String
  + premiumUri: String
}

SongAudio -- Song

class SongAnalytics <<struct>> {
  + playCount: usize
  + favouritesCount: usize
}

SongAnalytics -- Song

class Playlist <<struct>> {
  + id: Uuid
  + trackIds: Vec<Uuid>
  + metadata: PlaylistMetadata
  + analytics: PlaylistAnalytics
}

class PlaylistMetadata <<struct>> {
  + title: String
  + artistIds: Vec<Uuid>
  + ownerId: Uuid
  + isPublic: bool
}

PlaylistMetadata -- Playlist

class PlaylistAnalytics <<struct>> {
  + playCount: usize
  + favouritesCount: usize
}

PlaylistAnalytics -- Playlist

@enduml
