@startuml

left to right direction
hide empty members
skinparam BackgroundColor transparent

class User <<struct>> {
  + id: Uuid
  + credentials: UserCredentials
}

class UserCredentials <<struct>> {
  + username: String
  + email: String
  + password: String
}

UserCredentials -- User

class Listener <<struct>> {
  + metadata: ListenerMetadata
  + subscripion: ListenerSubscription
  + preferences: ListenerPreferences
}

Listener <|-- User

class ListenerMetadata <<struct>> {
  + dateOfBirth: Date
  + biography: String
  + gender: String
  + location: String
  + language: String
}

ListenerMetadata -- Listener

class ListenerContent <<struct>> {
  + favourites: ListenerFavourites
  + follows: ListenerFollows
}

ListenerContent -- Listener

class ListenerFavourites <<struct>> {
  + songIds: Vec<Uuid>
  + playlistIds: Vec<Uuid>
  + artistIds: Vec<Uuid>
}

ListenerFavourites -- ListenerContent

class ListenerFollows <<struct>> {
  + playlistIds: Vec<Uuid>
  + artistIds: Vec<Uuid>
}

ListenerFollows -- ListenerContent

enum ListenerSubscription <<enum>> {
}

ListenerSubscription -- Listener

class Free <<variant>> {
}

Free -- ListenerSubscription

class Premium <<variant>> {
  + started: DateTime
  + expires: DateTime
}

Premium -- ListenerSubscription

class Cancelled <<variant>> {
  + started: DateTime
  + cancelled: DateTime
}

Cancelled -- ListenerSubscription

class Expired <<variant>> {
  + started: DateTime
  + expired: DateTime
}

Expired -- ListenerSubscription

class ListenerPreferences <<struct>> {
  + darkModeEnabled: bool
  + explicitContentEnabled: bool
  + autoplayEnabled: bool
}

ListenerPreferences -- Listener

class Artist <<struct>> {
  + metadata: ArtistMetadata
}

Artist <|-- User

class ArtistMetadata <<struct>> {
  + displayName: String
  + socialLinks: Vec<String>
  + genres: Vec<String>
  + avatarUri: String
}

ArtistMetadata -- Artist

class ArtistContent <<struct>> {
  + singleIds: Vec<Uuid>
  + albumIds: Vec<Uuid>
}

ArtistContent -- Artist

class ArtistAnalytics <<struct>> {
  + playCount: usize
  + followerCount: usize
}

ArtistAnalytics -- Artist

class Song <<struct>> {
  + id: Uuid
  + metadata: SongMetadata
  + audio: SongAudio
}

class SongMetadata <<struct>> {
  + title: String
  + artistIds: Vec<Uuid>
  + duration: Duration
}

SongMetadata -- Song

class SongAudio <<struct>> {
  + basicUri: String
  + premiumUri: String
}

SongAudio -- Song

class Playlist <<struct>> {
  + id: Uuid
  + metadata: PlaylistMetadata
  + trackIds: Vec<Uuid>
}

class PlaylistMetadata <<struct>> {
  + title: String
  + artistIds: Vec<Uuid>
  + isPublic: bool
}

PlaylistMetadata -- Playlist

@enduml
