@startuml

left to right direction
hide empty members
skinparam BackgroundColor transparent

interface ListenerRepository <<trait>> {
    + save(listener: Listener)
    + remove(listenerId: Uuid)
    
    + getById(listenerId: Uuid) -> Option<Listener>
    + contains(listenerId: Uuid) -> bool
}

interface SongRepository <<trait>> {
    + save(song: Song)
    + remove(songId: Uuid)
    
    + getById(songId: Uuid) -> Option<Song>
    + contains(songId: Uuid) -> bool
}

interface PlaylistRepository <<trait>> {
    + save(playlist: Playlist)
    + remove(playlistId: Uuid)
    
    + getById(playlistId: Uuid) -> Option<Song>
    + contains(playlistId: Uuid) -> bool

    + show(listenerId: Uuid, paginationRequest: PaginationRequest)\n-> PaginationResponse<Playlist>
}

interface ArtistRepository <<trait>> {
    + getById(songId: Uuid) -> Option<Artist>
    + contains(songId: Uuid) -> bool
}

interface FavouritesRepository <<trait>> {
    + saveSong(listenerId: Uuid, songId: Uuid)
    + removeSong(listenerId: Uuid, songId: Uuid)
    + showSongs(listenerId: Uuid, songId: Uuid, \npaginationRequest: PaginationRequest) -> PaginationResponse<Song>

    + savePlaylist(listenerId: Uuid, playlistId: Uuid)
    + removePlaylist(listenerId: Uuid, playlistId: Uuid)
    + showPlaylists(listenerId: Uuid, playlistId: Uuid, \npaginationRequest: PaginationRequest) -> PaginationResponse<Playlist>

    + saveArtist(listenerId: Uuid, artistId: Uuid)
    + removeArtist(listenerId: Uuid, artistId: Uuid)
    + showPArtist(listenerId: Uuid, artistId: Uuid, \npaginationRequest: PaginationRequest) -> PaginationResponse<Artist>
}

interface LocalSongRepository <<trait>> {
    + save(listenerId: ListenerId, song: Song)
    + remove(listenerId: ListenerId, songId: Uuid)
    + get(listenerId: listenerId, songId: Uuid) -> Option<Song>
}

interface LocalPlaylistRepository <<trait>> {
    + save(listenerId: ListenerId, playlist: Playlist)
    + remove(listenerId: ListenerId, songId: Uuid)
    + get(listenerId: listenerId, playlistId: Uuid) -> Option<Playlist>
}

interface AuthTokenRepository <<trait>> {
    + save(authToken: String)
    + get() -> Option<String>
}

interface AuthTokenGenerator <<trait>> {
    + generate(listenerId: Uuid) -> String

    + verify(authToken: String) -> bool
    + invalidate(authToken: String)
    + getListenerId(authToken: String) -> Uuid
}

interface PasswordEncoder <<trait>> {
    + encode(rawPassword: String) -> String
    + verify(rawPassword: String, encodedPassword: String) -> bool
}

interface ResetAccountTokenGenerator <<trait>> {
    + generate(listenerId: Uuid) -> String
}

interface ResetAccountEmailComposser <<trait>> {
    + compose(listenerId: Uuid, username: String) -> String
}

interface ResetAccountEmailSender <<trait>> {
    + send(content: String, address: String)
}

interface UserCredentialsVerifier <<trait>> {
    + verify(credentials: UserCredentials) -> bool
}

class PaginationRequest <<struct>> {
    + pageIndex: usize
    + maxPageSize: usize
}

class PaginationResponse<T> <<struct>> {
    + items: Vec<T>

    + pageIndex: usize
    + maxPageIndex: usize
    + pageSize: usize
    + maxPageSize: usize
}

@enduml
